baseURL = "https://alex-onodugo.netlify.app"
languageCode = "en-us"
theme = "anubis"
title = "Alex Blog"
[Author]
name = "alex"
[Params]
author = "Alex Onodugo"
copyCodeButton = true
copyright = "Alex Onodugo"
dateFormat = "2006-01-02"
disableSummary = false
headTitle = "Home"
readMore = true
readNextPosts = 5
rssAsSocialIcon = true
[markup.goldmark.renderer]
unsafe = true
